[package]
name = "ficant-acceptance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
async-trait = { workspace = true }
ficant-application = { path = "../ficant-application" }
ficant-domain = { path = "../ficant-domain" }
ficant-runtime = { path = "../ficant-runtime" }
ficant-storage = { path = "../ficant-storage" }
minio = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
