[package]
name = "ficant-funding-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ficant-application = { path = "../ficant-application" }
ficant-contracts = { path = "../ficant-contracts" }
ficant-domain = { path = "../ficant-domain" }
prost = { workspace = true }

[lints]
workspace = true
