// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/market/v1/instrument.proto (package ficant.market.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { OwnerRef, Ulid, UnitRef, VersionRef } from "../../core/v1/common_pb";
import { file_ficant_core_v1_common } from "../../core/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/market/v1/instrument.proto.
 */
export const file_ficant_market_v1_instrument: GenFile = /*@__PURE__*/
  fileDesc("CiFmaWNhbnQvbWFya2V0L3YxL2luc3RydW1lbnQucHJvdG8SEGZpY2FudC5tYXJrZXQudjEinAIKCkluc3RydW1lbnQSKwoNaW5zdHJ1bWVudF9pZBgBIAEoCzIULmZpY2FudC5jb3JlLnYxLlVsaWQSDwoHdmVyc2lvbhgCIAEoBBInCgVvd25lchgDIAEoCzIYLmZpY2FudC5jb3JlLnYxLk93bmVyUmVmEi4KBGtpbmQYBCABKA4yIC5maWNhbnQubWFya2V0LnYxLkluc3RydW1lbnRLaW5kEg4KBm1hcmtldBgFIAEoCRIOCgZzeW1ib2wYBiABKAkSKQoIY3VycmVuY3kYByABKAsyFy5maWNhbnQuY29yZS52MS5Vbml0UmVmEiwKCGNhbGVuZGFyGAggASgLMhouZmljYW50LmNvcmUudjEuVmVyc2lvblJlZiqDAQoOSW5zdHJ1bWVudEtpbmQSHwobSU5TVFJVTUVOVF9LSU5EX1VOU1BFQ0lGSUVEEAASGAoUSU5TVFJVTUVOVF9LSU5EX0JPTkQQARIbChdJTlNUUlVNRU5UX0tJTkRfRlVUVVJFUxACEhkKFUlOU1RSVU1FTlRfS0lORF9PVEhFUhADYgZwcm90bzM", [file_ficant_core_v1_common]);

/**
 * Instrument is an immutable definition version.
 *
 * @generated from message ficant.market.v1.Instrument
 */
export type Instrument = Message<"ficant.market.v1.Instrument"> & {
  /**
   * @generated from field: ficant.core.v1.Ulid instrument_id = 1;
   */
  instrumentId?: Ulid;

  /**
   * @generated from field: uint64 version = 2;
   */
  version: bigint;

  /**
   * @generated from field: ficant.core.v1.OwnerRef owner = 3;
   */
  owner?: OwnerRef;

  /**
   * @generated from field: ficant.market.v1.InstrumentKind kind = 4;
   */
  kind: InstrumentKind;

  /**
   * @generated from field: string market = 5;
   */
  market: string;

  /**
   * @generated from field: string symbol = 6;
   */
  symbol: string;

  /**
   * @generated from field: ficant.core.v1.UnitRef currency = 7;
   */
  currency?: UnitRef;

  /**
   * @generated from field: ficant.core.v1.VersionRef calendar = 8;
   */
  calendar?: VersionRef;
};

/**
 * Describes the message ficant.market.v1.Instrument.
 * Use `create(InstrumentSchema)` to create a new message.
 */
export const InstrumentSchema: GenMessage<Instrument> = /*@__PURE__*/
  messageDesc(file_ficant_market_v1_instrument, 0);

/**
 * @generated from enum ficant.market.v1.InstrumentKind
 */
export enum InstrumentKind {
  /**
   * @generated from enum value: INSTRUMENT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INSTRUMENT_KIND_BOND = 1;
   */
  BOND = 1,

  /**
   * @generated from enum value: INSTRUMENT_KIND_FUTURES = 2;
   */
  FUTURES = 2,

  /**
   * @generated from enum value: INSTRUMENT_KIND_OTHER = 3;
   */
  OTHER = 3,
}

/**
 * Describes the enum ficant.market.v1.InstrumentKind.
 */
export const InstrumentKindSchema: GenEnum<InstrumentKind> = /*@__PURE__*/
  enumDesc(file_ficant_market_v1_instrument, 0);

