// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/market/v1/rule.proto (package ficant.market.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MarketTime, OwnerRef, Sha256, Ulid } from "../../core/v1/common_pb";
import { file_ficant_core_v1_common } from "../../core/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/market/v1/rule.proto.
 */
export const file_ficant_market_v1_rule: GenFile = /*@__PURE__*/
  fileDesc("ChtmaWNhbnQvbWFya2V0L3YxL3J1bGUucHJvdG8SEGZpY2FudC5tYXJrZXQudjEigAMKDk1hcmtldFJ1bGVQYWNrEioKDHJ1bGVfcGFja19pZBgBIAEoCzIULmZpY2FudC5jb3JlLnYxLlVsaWQSDwoHdmVyc2lvbhgCIAEoBBInCgVvd25lchgDIAEoCzIYLmZpY2FudC5jb3JlLnYxLk93bmVyUmVmEg4KBm1hcmtldBgEIAEoCRIRCglydWxlX3R5cGUYBSABKAkSDgoGc291cmNlGAYgASgJEjIKDmVmZmVjdGl2ZV9mcm9tGAcgASgLMhouZmljYW50LmNvcmUudjEuTWFya2V0VGltZRIwCgxlZmZlY3RpdmVfdG8YCCABKAsyGi5maWNhbnQuY29yZS52MS5NYXJrZXRUaW1lEkEKE3ZlcmlmaWNhdGlvbl9zdGF0dXMYCSABKA4yJC5maWNhbnQubWFya2V0LnYxLlZlcmlmaWNhdGlvblN0YXR1cxIsCgxjb250ZW50X2hhc2gYCiABKAsyFi5maWNhbnQuY29yZS52MS5TaGEyNTYqoQEKElZlcmlmaWNhdGlvblN0YXR1cxIjCh9WRVJJRklDQVRJT05fU1RBVFVTX1VOU1BFQ0lGSUVEEAASIgoeVkVSSUZJQ0FUSU9OX1NUQVRVU19VTlZFUklGSUVEEAESIAocVkVSSUZJQ0FUSU9OX1NUQVRVU19WRVJJRklFRBACEiAKHFZFUklGSUNBVElPTl9TVEFUVVNfUkVKRUNURUQQA2IGcHJvdG8z", [file_ficant_core_v1_common]);

/**
 * MarketRulePack records a verified external rule input. It does not execute
 * pricing, curve construction, duration, DV01, or any Phase 2 algorithm.
 *
 * @generated from message ficant.market.v1.MarketRulePack
 */
export type MarketRulePack = Message<"ficant.market.v1.MarketRulePack"> & {
  /**
   * @generated from field: ficant.core.v1.Ulid rule_pack_id = 1;
   */
  rulePackId?: Ulid;

  /**
   * @generated from field: uint64 version = 2;
   */
  version: bigint;

  /**
   * @generated from field: ficant.core.v1.OwnerRef owner = 3;
   */
  owner?: OwnerRef;

  /**
   * @generated from field: string market = 4;
   */
  market: string;

  /**
   * @generated from field: string rule_type = 5;
   */
  ruleType: string;

  /**
   * @generated from field: string source = 6;
   */
  source: string;

  /**
   * @generated from field: ficant.core.v1.MarketTime effective_from = 7;
   */
  effectiveFrom?: MarketTime;

  /**
   * @generated from field: ficant.core.v1.MarketTime effective_to = 8;
   */
  effectiveTo?: MarketTime;

  /**
   * @generated from field: ficant.market.v1.VerificationStatus verification_status = 9;
   */
  verificationStatus: VerificationStatus;

  /**
   * @generated from field: ficant.core.v1.Sha256 content_hash = 10;
   */
  contentHash?: Sha256;
};

/**
 * Describes the message ficant.market.v1.MarketRulePack.
 * Use `create(MarketRulePackSchema)` to create a new message.
 */
export const MarketRulePackSchema: GenMessage<MarketRulePack> = /*@__PURE__*/
  messageDesc(file_ficant_market_v1_rule, 0);

/**
 * @generated from enum ficant.market.v1.VerificationStatus
 */
export enum VerificationStatus {
  /**
   * @generated from enum value: VERIFICATION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: VERIFICATION_STATUS_UNVERIFIED = 1;
   */
  UNVERIFIED = 1,

  /**
   * @generated from enum value: VERIFICATION_STATUS_VERIFIED = 2;
   */
  VERIFIED = 2,

  /**
   * @generated from enum value: VERIFICATION_STATUS_REJECTED = 3;
   */
  REJECTED = 3,
}

/**
 * Describes the enum ficant.market.v1.VerificationStatus.
 */
export const VerificationStatusSchema: GenEnum<VerificationStatus> = /*@__PURE__*/
  enumDesc(file_ficant_market_v1_rule, 0);

