// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/market/v1/tax_rule.proto (package ficant.market.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DecimalValue } from "../../core/v1/common_pb";
import { file_ficant_core_v1_common } from "../../core/v1/common_pb";
import type { BondTaxAttributes } from "./definition_pb";
import { file_ficant_market_v1_definition } from "./definition_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/market/v1/tax_rule.proto.
 */
export const file_ficant_market_v1_tax_rule: GenFile = /*@__PURE__*/
  fileDesc("Ch9maWNhbnQvbWFya2V0L3YxL3RheF9ydWxlLnByb3RvEhBmaWNhbnQubWFya2V0LnYxIkgKC1RheFJ1bGVQYWNrEjkKDGNvdXBvbl9ydWxlcxgBIAMoCzIjLmZpY2FudC5tYXJrZXQudjEuQm9uZENvdXBvblRheFJ1bGUiuQEKEUJvbmRDb3Vwb25UYXhSdWxlEhgKEGZpcnN0X2lzc3VlX2Zyb20YASABKAkSFgoOZmlyc3RfaXNzdWVfdG8YAiABKAkSOwoOdGF4X2F0dHJpYnV0ZXMYAyABKAsyIy5maWNhbnQubWFya2V0LnYxLkJvbmRUYXhBdHRyaWJ1dGVzEjUKBXJhdGVzGAQgAygLMiYuZmljYW50Lm1hcmtldC52MS5TdWJqZWN0Q291cG9uVGF4UmF0ZSKKAQoUU3ViamVjdENvdXBvblRheFJhdGUSHwoXdmFsdWVfYWRkZWRfdGF4X3Byb2ZpbGUYASABKAkSGgoSaW5jb21lX3RheF9wcm9maWxlGAIgASgJEjUKD2NvdXBvbl90YXhfcmF0ZRgDIAEoCzIcLmZpY2FudC5jb3JlLnYxLkRlY2ltYWxWYWx1ZWIGcHJvdG8z", [file_ficant_core_v1_common, file_ficant_market_v1_definition]);

/**
 * TaxRulePack is L3 content. It selects a coupon tax rate from the Bond's
 * first issuance interval, its L2 tax attributes, and the exact Subject tax
 * treatment pair. It contains no Subject identity or market-specific rate in
 * the generic contracts.
 *
 * @generated from message ficant.market.v1.TaxRulePack
 */
export type TaxRulePack = Message<"ficant.market.v1.TaxRulePack"> & {
  /**
   * @generated from field: repeated ficant.market.v1.BondCouponTaxRule coupon_rules = 1;
   */
  couponRules: BondCouponTaxRule[];
};

/**
 * Describes the message ficant.market.v1.TaxRulePack.
 * Use `create(TaxRulePackSchema)` to create a new message.
 */
export const TaxRulePackSchema: GenMessage<TaxRulePack> = /*@__PURE__*/
  messageDesc(file_ficant_market_v1_tax_rule, 0);

/**
 * @generated from message ficant.market.v1.BondCouponTaxRule
 */
export type BondCouponTaxRule = Message<"ficant.market.v1.BondCouponTaxRule"> & {
  /**
   * Inclusive ISO-8601 date. Rules are sorted by this field.
   *
   * @generated from field: string first_issue_from = 1;
   */
  firstIssueFrom: string;

  /**
   * Exclusive ISO-8601 date. An empty value means this rule is unbounded above.
   *
   * @generated from field: string first_issue_to = 2;
   */
  firstIssueTo: string;

  /**
   * @generated from field: ficant.market.v1.BondTaxAttributes tax_attributes = 3;
   */
  taxAttributes?: BondTaxAttributes;

  /**
   * @generated from field: repeated ficant.market.v1.SubjectCouponTaxRate rates = 4;
   */
  rates: SubjectCouponTaxRate[];
};

/**
 * Describes the message ficant.market.v1.BondCouponTaxRule.
 * Use `create(BondCouponTaxRuleSchema)` to create a new message.
 */
export const BondCouponTaxRuleSchema: GenMessage<BondCouponTaxRule> = /*@__PURE__*/
  messageDesc(file_ficant_market_v1_tax_rule, 1);

/**
 * @generated from message ficant.market.v1.SubjectCouponTaxRate
 */
export type SubjectCouponTaxRate = Message<"ficant.market.v1.SubjectCouponTaxRate"> & {
  /**
   * @generated from field: string value_added_tax_profile = 1;
   */
  valueAddedTaxProfile: string;

  /**
   * @generated from field: string income_tax_profile = 2;
   */
  incomeTaxProfile: string;

  /**
   * @generated from field: ficant.core.v1.DecimalValue coupon_tax_rate = 3;
   */
  couponTaxRate?: DecimalValue;
};

/**
 * Describes the message ficant.market.v1.SubjectCouponTaxRate.
 * Use `create(SubjectCouponTaxRateSchema)` to create a new message.
 */
export const SubjectCouponTaxRateSchema: GenMessage<SubjectCouponTaxRate> = /*@__PURE__*/
  messageDesc(file_ficant_market_v1_tax_rule, 2);

