// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/research/v1/coverage.proto (package ficant.research.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DecimalValue } from "../../core/v1/common_pb";
import { file_ficant_core_v1_common } from "../../core/v1/common_pb";
import type { PriceSourceType } from "../../market/v1/data_source_pb";
import { file_ficant_market_v1_data_source } from "../../market/v1/data_source_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/research/v1/coverage.proto.
 */
export const file_ficant_research_v1_coverage: GenFile = /*@__PURE__*/
  fileDesc("CiFmaWNhbnQvcmVzZWFyY2gvdjEvY292ZXJhZ2UucHJvdG8SEmZpY2FudC5yZXNlYXJjaC52MSJgChBQcmljZVNvdXJjZUNvdW50EjYKC3NvdXJjZV90eXBlGAEgASgOMiEuZmljYW50Lm1hcmtldC52MS5QcmljZVNvdXJjZVR5cGUSFAoMcmVjb3JkX2NvdW50GAIgASgEIlkKElByaWNlU291cmNlU3VtbWFyeRI0CgZjb3VudHMYASADKAsyJC5maWNhbnQucmVzZWFyY2gudjEuUHJpY2VTb3VyY2VDb3VudBINCgVtaXhlZBgCIAEoCCKgAwoTQ292ZXJhZ2VEZWNsYXJhdGlvbhIfChdpbXBvcnRlZF9wb3NpdGlvbl9jb3VudBgBIAEoBBIkChxwYXJ0aWNpcGF0aW5nX3Bvc2l0aW9uX2NvdW50GAIgASgEEksKJWltcG9ydGVkX2dyb3NzX2Vjb25vbWljX3ZhbHVlX2J5X3VuaXQYAyADKAsyHC5maWNhbnQuY29yZS52MS5EZWNpbWFsVmFsdWUSUAoqcGFydGljaXBhdGluZ19ncm9zc19lY29ub21pY192YWx1ZV9ieV91bml0GAQgAygLMhwuZmljYW50LmNvcmUudjEuRGVjaW1hbFZhbHVlEisKI21pc3NpbmdfY3JpdGljYWxfZmllbGRfcmVjb3JkX2NvdW50GAUgASgEEkEKEXNvdXJjZV9jb25maWRlbmNlGAYgASgLMiYuZmljYW50LnJlc2VhcmNoLnYxLlByaWNlU291cmNlU3VtbWFyeRIzCitkaXN0aW5jdF9leHRlcm5hbF9kYXRhX3NvdXJjZV92ZXJzaW9uX2NvdW50GAcgASgEYgZwcm90bzM", [file_ficant_core_v1_common, file_ficant_market_v1_data_source]);

/**
 * @generated from message ficant.research.v1.PriceSourceCount
 */
export type PriceSourceCount = Message<"ficant.research.v1.PriceSourceCount"> & {
  /**
   * @generated from field: ficant.market.v1.PriceSourceType source_type = 1;
   */
  sourceType: PriceSourceType;

  /**
   * @generated from field: uint64 record_count = 2;
   */
  recordCount: bigint;
};

/**
 * Describes the message ficant.research.v1.PriceSourceCount.
 * Use `create(PriceSourceCountSchema)` to create a new message.
 */
export const PriceSourceCountSchema: GenMessage<PriceSourceCount> = /*@__PURE__*/
  messageDesc(file_ficant_research_v1_coverage, 0);

/**
 * @generated from message ficant.research.v1.PriceSourceSummary
 */
export type PriceSourceSummary = Message<"ficant.research.v1.PriceSourceSummary"> & {
  /**
   * @generated from field: repeated ficant.research.v1.PriceSourceCount counts = 1;
   */
  counts: PriceSourceCount[];

  /**
   * @generated from field: bool mixed = 2;
   */
  mixed: boolean;
};

/**
 * Describes the message ficant.research.v1.PriceSourceSummary.
 * Use `create(PriceSourceSummarySchema)` to create a new message.
 */
export const PriceSourceSummarySchema: GenMessage<PriceSourceSummary> = /*@__PURE__*/
  messageDesc(file_ficant_research_v1_coverage, 1);

/**
 * @generated from message ficant.research.v1.CoverageDeclaration
 */
export type CoverageDeclaration = Message<"ficant.research.v1.CoverageDeclaration"> & {
  /**
   * @generated from field: uint64 imported_position_count = 1;
   */
  importedPositionCount: bigint;

  /**
   * @generated from field: uint64 participating_position_count = 2;
   */
  participatingPositionCount: bigint;

  /**
   * @generated from field: repeated ficant.core.v1.DecimalValue imported_gross_economic_value_by_unit = 3;
   */
  importedGrossEconomicValueByUnit: DecimalValue[];

  /**
   * @generated from field: repeated ficant.core.v1.DecimalValue participating_gross_economic_value_by_unit = 4;
   */
  participatingGrossEconomicValueByUnit: DecimalValue[];

  /**
   * @generated from field: uint64 missing_critical_field_record_count = 5;
   */
  missingCriticalFieldRecordCount: bigint;

  /**
   * @generated from field: ficant.research.v1.PriceSourceSummary source_confidence = 6;
   */
  sourceConfidence?: PriceSourceSummary;

  /**
   * @generated from field: uint64 distinct_external_data_source_version_count = 7;
   */
  distinctExternalDataSourceVersionCount: bigint;
};

/**
 * Describes the message ficant.research.v1.CoverageDeclaration.
 * Use `create(CoverageDeclarationSchema)` to create a new message.
 */
export const CoverageDeclarationSchema: GenMessage<CoverageDeclaration> = /*@__PURE__*/
  messageDesc(file_ficant_research_v1_coverage, 2);

