// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/research/v1/journal.proto (package ficant.research.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MarketTime, Sha256, Ulid } from "../../core/v1/common_pb";
import { file_ficant_core_v1_common } from "../../core/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/research/v1/journal.proto.
 */
export const file_ficant_research_v1_journal: GenFile = /*@__PURE__*/
  fileDesc("CiBmaWNhbnQvcmVzZWFyY2gvdjEvam91cm5hbC5wcm90bxISZmljYW50LnJlc2VhcmNoLnYxIvUCCgpSdW5Kb3VybmFsEi4KEGpvdXJuYWxfZXZlbnRfaWQYASABKAsyFC5maWNhbnQuY29yZS52MS5VbGlkEiQKBnJ1bl9pZBgCIAEoCzIULmZpY2FudC5jb3JlLnYxLlVsaWQSEAoIc2VxdWVuY2UYAyABKAQSOAoKZXZlbnRfdHlwZRgEIAEoDjIkLmZpY2FudC5yZXNlYXJjaC52MS5Kb3VybmFsRXZlbnRUeXBlEi8KC29jY3VycmVkX2F0GAUgASgLMhouZmljYW50LmNvcmUudjEuTWFya2V0VGltZRIUCgxwYXlsb2FkX3R5cGUYBiABKAkSFgoOcGF5bG9hZF9zY2hlbWEYByABKAkSDwoHcGF5bG9hZBgIIAEoDBIpCglwcmV2X2hhc2gYCSABKAsyFi5maWNhbnQuY29yZS52MS5TaGEyNTYSKgoKZXZlbnRfaGFzaBgKIAEoCzIWLmZpY2FudC5jb3JlLnYxLlNoYTI1NirFAgoQSm91cm5hbEV2ZW50VHlwZRIiCh5KT1VSTkFMX0VWRU5UX1RZUEVfVU5TUEVDSUZJRUQQABIiCh5KT1VSTkFMX0VWRU5UX1RZUEVfUlVOX0NSRUFURUQQARIiCh5KT1VSTkFMX0VWRU5UX1RZUEVfUlVOX1NUQVJURUQQAhIkCiBKT1VSTkFMX0VWRU5UX1RZUEVfUlVOX1NVQ0NFRURFRBADEiEKHUpPVVJOQUxfRVZFTlRfVFlQRV9SVU5fRkFJTEVEEAQSJAogSk9VUk5BTF9FVkVOVF9UWVBFX1JVTl9DQU5DRUxMRUQQBRIpCiVKT1VSTkFMX0VWRU5UX1RZUEVfQVJUSUZBQ1RfUFVCTElTSEVEEAYSKwonSk9VUk5BTF9FVkVOVF9UWVBFX1NJR05BTF9TRVRfUFVCTElTSEVEEAdiBnByb3RvMw", [file_ficant_core_v1_common]);

/**
 * @generated from message ficant.research.v1.RunJournal
 */
export type RunJournal = Message<"ficant.research.v1.RunJournal"> & {
  /**
   * @generated from field: ficant.core.v1.Ulid journal_event_id = 1;
   */
  journalEventId?: Ulid;

  /**
   * @generated from field: ficant.core.v1.Ulid run_id = 2;
   */
  runId?: Ulid;

  /**
   * @generated from field: uint64 sequence = 3;
   */
  sequence: bigint;

  /**
   * @generated from field: ficant.research.v1.JournalEventType event_type = 4;
   */
  eventType: JournalEventType;

  /**
   * @generated from field: ficant.core.v1.MarketTime occurred_at = 5;
   */
  occurredAt?: MarketTime;

  /**
   * @generated from field: string payload_type = 6;
   */
  payloadType: string;

  /**
   * @generated from field: string payload_schema = 7;
   */
  payloadSchema: string;

  /**
   * @generated from field: bytes payload = 8;
   */
  payload: Uint8Array;

  /**
   * @generated from field: ficant.core.v1.Sha256 prev_hash = 9;
   */
  prevHash?: Sha256;

  /**
   * @generated from field: ficant.core.v1.Sha256 event_hash = 10;
   */
  eventHash?: Sha256;
};

/**
 * Describes the message ficant.research.v1.RunJournal.
 * Use `create(RunJournalSchema)` to create a new message.
 */
export const RunJournalSchema: GenMessage<RunJournal> = /*@__PURE__*/
  messageDesc(file_ficant_research_v1_journal, 0);

/**
 * @generated from enum ficant.research.v1.JournalEventType
 */
export enum JournalEventType {
  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_RUN_CREATED = 1;
   */
  RUN_CREATED = 1,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_RUN_STARTED = 2;
   */
  RUN_STARTED = 2,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_RUN_SUCCEEDED = 3;
   */
  RUN_SUCCEEDED = 3,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_RUN_FAILED = 4;
   */
  RUN_FAILED = 4,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_RUN_CANCELLED = 5;
   */
  RUN_CANCELLED = 5,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_ARTIFACT_PUBLISHED = 6;
   */
  ARTIFACT_PUBLISHED = 6,

  /**
   * @generated from enum value: JOURNAL_EVENT_TYPE_SIGNAL_SET_PUBLISHED = 7;
   */
  SIGNAL_SET_PUBLISHED = 7,
}

/**
 * Describes the enum ficant.research.v1.JournalEventType.
 */
export const JournalEventTypeSchema: GenEnum<JournalEventType> = /*@__PURE__*/
  enumDesc(file_ficant_research_v1_journal, 0);

