// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/research/v1/signal.proto (package ficant.research.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { LineageRef, MarketTime, OwnerRef, Ulid, VersionRef } from "../../core/v1/common_pb";
import { file_ficant_core_v1_common } from "../../core/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/research/v1/signal.proto.
 */
export const file_ficant_research_v1_signal: GenFile = /*@__PURE__*/
  fileDesc("Ch9maWNhbnQvcmVzZWFyY2gvdjEvc2lnbmFsLnByb3RvEhJmaWNhbnQucmVzZWFyY2gudjEi7QMKCVNpZ25hbFNldBIrCg1zaWduYWxfc2V0X2lkGAEgASgLMhQuZmljYW50LmNvcmUudjEuVWxpZBInCgVvd25lchgCIAEoCzIYLmZpY2FudC5jb3JlLnYxLk93bmVyUmVmEiwKCGFydGlmYWN0GAMgASgLMhouZmljYW50LmNvcmUudjEuTGluZWFnZVJlZhIvChFleHBlcmltZW50X3J1bl9pZBgEIAEoCzIULmZpY2FudC5jb3JlLnYxLlVsaWQSMQoNZGF0YV9zbmFwc2hvdBgFIAEoCzIaLmZpY2FudC5jb3JlLnYxLkxpbmVhZ2VSZWYSNQoRdW5pdmVyc2Vfc25hcHNob3QYBiABKAsyGi5maWNhbnQuY29yZS52MS5MaW5lYWdlUmVmEi4KCnJ1bGVfcGFja3MYByADKAsyGi5maWNhbnQuY29yZS52MS5WZXJzaW9uUmVmEjMKD2lucHV0X2FydGlmYWN0cxgIIAMoCzIaLmZpY2FudC5jb3JlLnYxLkxpbmVhZ2VSZWYSLgoKdmFsaWRfZnJvbRgJIAEoCzIaLmZpY2FudC5jb3JlLnYxLk1hcmtldFRpbWUSLAoIdmFsaWRfdG8YCiABKAsyGi5maWNhbnQuY29yZS52MS5NYXJrZXRUaW1lYgZwcm90bzM", [file_ficant_core_v1_common]);

/**
 * SignalSet is an immutable, lineaged artifact subtype; it is not an Order.
 *
 * @generated from message ficant.research.v1.SignalSet
 */
export type SignalSet = Message<"ficant.research.v1.SignalSet"> & {
  /**
   * @generated from field: ficant.core.v1.Ulid signal_set_id = 1;
   */
  signalSetId?: Ulid;

  /**
   * @generated from field: ficant.core.v1.OwnerRef owner = 2;
   */
  owner?: OwnerRef;

  /**
   * @generated from field: ficant.core.v1.LineageRef artifact = 3;
   */
  artifact?: LineageRef;

  /**
   * @generated from field: ficant.core.v1.Ulid experiment_run_id = 4;
   */
  experimentRunId?: Ulid;

  /**
   * @generated from field: ficant.core.v1.LineageRef data_snapshot = 5;
   */
  dataSnapshot?: LineageRef;

  /**
   * @generated from field: ficant.core.v1.LineageRef universe_snapshot = 6;
   */
  universeSnapshot?: LineageRef;

  /**
   * @generated from field: repeated ficant.core.v1.VersionRef rule_packs = 7;
   */
  rulePacks: VersionRef[];

  /**
   * @generated from field: repeated ficant.core.v1.LineageRef input_artifacts = 8;
   */
  inputArtifacts: LineageRef[];

  /**
   * @generated from field: ficant.core.v1.MarketTime valid_from = 9;
   */
  validFrom?: MarketTime;

  /**
   * @generated from field: ficant.core.v1.MarketTime valid_to = 10;
   */
  validTo?: MarketTime;
};

/**
 * Describes the message ficant.research.v1.SignalSet.
 * Use `create(SignalSetSchema)` to create a new message.
 */
export const SignalSetSchema: GenMessage<SignalSet> = /*@__PURE__*/
  messageDesc(file_ficant_research_v1_signal, 0);

