// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file ficant/core/v1/error.proto (package ficant.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ficant/core/v1/error.proto.
 */
export const file_ficant_core_v1_error: GenFile = /*@__PURE__*/
  fileDesc("ChpmaWNhbnQvY29yZS92MS9lcnJvci5wcm90bxIOZmljYW50LmNvcmUudjEiNAoORmllbGRWaW9sYXRpb24SDQoFZmllbGQYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkivAEKC0Vycm9yRGV0YWlsEicKBGNvZGUYASABKA4yGS5maWNhbnQuY29yZS52MS5FcnJvckNvZGUSDwoHbWVzc2FnZRgCIAEoCRIQCgh0cmFjZV9pZBgDIAEoCRIRCglyZXRyeWFibGUYBCABKAgSFAoMcmVzb3VyY2VfcmVmGAUgASgJEjgKEGZpZWxkX3Zpb2xhdGlvbnMYBiADKAsyHi5maWNhbnQuY29yZS52MS5GaWVsZFZpb2xhdGlvbiqkAwoJRXJyb3JDb2RlEhoKFkVSUk9SX0NPREVfVU5TUEVDSUZJRUQQABIgChxFUlJPUl9DT0RFX1ZBTElEQVRJT05fRkFJTEVEEAESGAoURVJST1JfQ09ERV9OT1RfRk9VTkQQAhIdChlFUlJPUl9DT0RFX0FMUkVBRFlfRVhJU1RTEAMSHwobRVJST1JfQ09ERV9WRVJTSU9OX0NPTkZMSUNUEAQSIwofRVJST1JfQ09ERV9DT05DVVJSRU5DWV9DT05GTElDVBAFEiIKHkVSUk9SX0NPREVfSU1NVVRBQkxFX1ZJT0xBVElPThAGEiEKHUVSUk9SX0NPREVfTElORUFHRV9JTkNPTVBMRVRFEAcSHAoYRVJST1JfQ09ERV9IQVNIX01JU01BVENIEAgSHgoaRVJST1JfQ09ERV9VTkFVVEhFTlRJQ0FURUQQCRIYChRFUlJPUl9DT0RFX0ZPUkJJRERFThAKEiIKHkVSUk9SX0NPREVfU1RPUkFHRV9VTkFWQUlMQUJMRRALEhcKE0VSUk9SX0NPREVfSU5URVJOQUwQDGIGcHJvdG8z");

/**
 * @generated from message ficant.core.v1.FieldViolation
 */
export type FieldViolation = Message<"ficant.core.v1.FieldViolation"> & {
  /**
   * @generated from field: string field = 1;
   */
  field: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message ficant.core.v1.FieldViolation.
 * Use `create(FieldViolationSchema)` to create a new message.
 */
export const FieldViolationSchema: GenMessage<FieldViolation> = /*@__PURE__*/
  messageDesc(file_ficant_core_v1_error, 0);

/**
 * ErrorDetail is attached to a gRPC status. message is safe for clients and
 * must not expose SQL, bucket names, credentials, stack traces, or raw causes.
 *
 * @generated from message ficant.core.v1.ErrorDetail
 */
export type ErrorDetail = Message<"ficant.core.v1.ErrorDetail"> & {
  /**
   * @generated from field: ficant.core.v1.ErrorCode code = 1;
   */
  code: ErrorCode;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string trace_id = 3;
   */
  traceId: string;

  /**
   * @generated from field: bool retryable = 4;
   */
  retryable: boolean;

  /**
   * @generated from field: string resource_ref = 5;
   */
  resourceRef: string;

  /**
   * @generated from field: repeated ficant.core.v1.FieldViolation field_violations = 6;
   */
  fieldViolations: FieldViolation[];
};

/**
 * Describes the message ficant.core.v1.ErrorDetail.
 * Use `create(ErrorDetailSchema)` to create a new message.
 */
export const ErrorDetailSchema: GenMessage<ErrorDetail> = /*@__PURE__*/
  messageDesc(file_ficant_core_v1_error, 1);

/**
 * @generated from enum ficant.core.v1.ErrorCode
 */
export enum ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_CODE_VALIDATION_FAILED = 1;
   */
  VALIDATION_FAILED = 1,

  /**
   * @generated from enum value: ERROR_CODE_NOT_FOUND = 2;
   */
  NOT_FOUND = 2,

  /**
   * @generated from enum value: ERROR_CODE_ALREADY_EXISTS = 3;
   */
  ALREADY_EXISTS = 3,

  /**
   * @generated from enum value: ERROR_CODE_VERSION_CONFLICT = 4;
   */
  VERSION_CONFLICT = 4,

  /**
   * @generated from enum value: ERROR_CODE_CONCURRENCY_CONFLICT = 5;
   */
  CONCURRENCY_CONFLICT = 5,

  /**
   * @generated from enum value: ERROR_CODE_IMMUTABLE_VIOLATION = 6;
   */
  IMMUTABLE_VIOLATION = 6,

  /**
   * @generated from enum value: ERROR_CODE_LINEAGE_INCOMPLETE = 7;
   */
  LINEAGE_INCOMPLETE = 7,

  /**
   * @generated from enum value: ERROR_CODE_HASH_MISMATCH = 8;
   */
  HASH_MISMATCH = 8,

  /**
   * @generated from enum value: ERROR_CODE_UNAUTHENTICATED = 9;
   */
  UNAUTHENTICATED = 9,

  /**
   * @generated from enum value: ERROR_CODE_FORBIDDEN = 10;
   */
  FORBIDDEN = 10,

  /**
   * @generated from enum value: ERROR_CODE_STORAGE_UNAVAILABLE = 11;
   */
  STORAGE_UNAVAILABLE = 11,

  /**
   * @generated from enum value: ERROR_CODE_INTERNAL = 12;
   */
  INTERNAL = 12,
}

/**
 * Describes the enum ficant.core.v1.ErrorCode.
 */
export const ErrorCodeSchema: GenEnum<ErrorCode> = /*@__PURE__*/
  enumDesc(file_ficant_core_v1_error, 0);

