[package]
name = "ficant-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
ficant-domain = { path = "../ficant-domain" }
ficant-runtime = { path = "../ficant-runtime" }
ring = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
