[package]
name = "ficant-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
ficant-application = { path = "../ficant-application" }
ficant-contracts = { path = "../ficant-contracts" }
ficant-domain = { path = "../ficant-domain" }
ficant-runtime = { path = "../ficant-runtime" }
object_store = { workspace = true }
prost = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
ficant-fixed-income-native = { path = "../ficant-fixed-income-native" }
serde_json = { workspace = true }
