[package]
name = "ficant-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
ficant-application = { path = "../ficant-application" }
ficant-domain = { path = "../ficant-domain" }
minio = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
