[package]
name = "ficant-native-nodes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ficant-api = { path = "../ficant-api" }
ficant-contracts = { path = "../ficant-contracts" }
ficant-domain = { path = "../ficant-domain" }
ficant-fixed-income-native = { path = "../ficant-fixed-income-native" }
ficant-runtime = { path = "../ficant-runtime" }
prost = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
prost-types = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
